blog1/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog1.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

app_name = 'blog1'

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    #Обработчики приложения блога.
    #post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

firstblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls', namespace='blog1'))
]

blog1/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog1_posts')

    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog1:post_detail', args=[self.publish.year, self.publish.month,
                                                  self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog1/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    имя = forms.CharField(max_length=25)
    email = forms.EmailField()
    кому = forms.EmailField()
    комментарий = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    запрос = forms.CharField()

blog1/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404

from firstblog.data_dict import email_data
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # По 3 статьи на страницу.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница - не целое число, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее кол-во страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog1/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


# Этот класс - тоже самое, что и функция post_list выше.
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog1/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    # Cписок активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # Пользователь оставил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаём комментарий, но пока не сохраняем в базу данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()
    # Формирование списка похожих статей.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog1/post/detail.html', {'post': post,
                                                      'comments': comments,
                                                      'new_comment': new_comment,
                                                      'comment_form': comment_form,
                                                      'similar_posts': similar_posts})


def post_share(request, post_id):
    # Получение статьи по идентификатору
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию
            cd = form.cleaned_data
            # Отправка электронной почты.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) рекомендует вам почитать статью ' \
                      '"{}"'.format(cd['имя'], cd['email'], post.title)
            message = 'Читайте "{}" по ссылке {}\n\n{} также добавил комментарий: ' \
                      '{}'.format(post.title, post_url, cd['имя'], cd['комментарий'])
            send_mail(subject, message, email_data.get('Email'), [cd['кому']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog1/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog1/post/search.html', {'form': form,
                                                      'query': query,
                                                      'results': results})

blog1/templates/blog1/base.html
{% load blog1_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog1.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>Мой блог</h2>
        <p>Этой мой блог. На данный момент, количество моих постов равно {% total_posts %} =)</p>
        <p><a href="{% url "blog1:post_feed" %}">Подпишись на мою RSS рассылку</a></p>
        <h3>Последние посты</h3>
        {% show_latest_posts 2 %}
        <h3>Самые комментируемые посты</h3>
        {% get_most_commented_posts 1 as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog1/templates/blog1/post/detail.html
{% extends "blog1/base.html" %}
{% load blog1_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
        Теги:
            {% for tag in post.tags.all %}
                <a href="{% url "blog1:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
    <p class="date">Опубликовано {{ post.publish }}, автор {{ post.author }}</p>
    {{ post.body|markdown }}

    <p>
        <a href="{% url "blog1:post_share" post.id %}">Поделиться постом</a>
    </p>

    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Похожих постов ещё нет.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>Всего комментариев: {{ total_comments }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} от {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>Комментариев ещё нет.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Ваш комментарий добавлен.</h2>
    {% else %}
        <h2>Добавить новый комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

blog1/templates/blog1/post/latest_posts.html
<ul>
{% for post in latest_posts %}
<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>

blog1/templates/blog1/post/list.html
{% extends "blog1/base.html" %}
{% load blog1_tags %}
{% block title %}Мой Блог{% endblock %}
{% block content %}
    <h1>Мой Блог</h1>
    {% if tag %}
        <h2>Посты с тегом "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            Теги:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog1:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
        </p>
        <p class="date">Опубликовано {{ post.publish }}, автор {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{#        {% include "pagination.html" with page=page_obj %}#}
{% endblock %}

blog1/templates/blog1/post/search.html
{% extends "blog1/base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
  {% if query %}
    <h1>Посты, содержащие "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Найдено {{ total_results }} результатов{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>По данному запросу ничего не найдено.</p>
    {% endfor %}
    <p><a href="{% url "blog1:post_search" %}">Искать снова</a></p>
  {% else %}
    <h1>Поиск постов</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Искать">
    </form>
  {% endif %}
{% endblock %}

blog1/templates/blog1/post/share.html
{% extends "blog1/base.html" %}
{% block title %}Поделиться постом{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлен!</h1>
        <p>"{{ post.title }}" был успешно отправлен по адресу {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Поделиться "{{ post.title }}" по e-mail</h1>
        <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog1/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>